# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/secondproject',
                'doc_host': 'https://michaeldini.github.io',
                'git_url': 'https://github.com/michaeldini/secondproject',
                'lib_path': 'secondproject'},
  'syms': {'secondproject.core': {'secondproject.core.foo': ('core.html#foo', 'secondproject/core.py')}}}
